create database youtube_db;
use youtube_db;
create table channels(channel_id int,user_id int,channel_name varchar(50),description text,subscribers BIGINT,created_at DATETIME);
desc channels;
create table Videos( video_id INT, channel_id INT, title VARCHAR(150),description TEXT,views BIGINT,visibility ENUM('public','private','unlisted'), uploaded_at TIMESTAMP);
desc Videos;
create table Comments(comment_id INT, video_id INT,  user_id INT,comment text,likes INT,commented_at DATETIME,number_of_comments bigint);
desc Comments;
create table Likes( like_id INT, user_id INT,video_id INT, like_type ENUM('like','dislike'),reacted_at TIMESTAMP,reaction SET('Like','Dislike','Love'),reaction_source SET('Mobile','Web','TV'));
desc Likes;
create table Subscription( subscription_id INT,subscription_plan ENUM('Free','Premium','Family'),notification_type SET('All','Personalized','None'),auto_renew BOOLEAN,price DECIMAL(6,2),discount_percentage FLOAT,subscription_start DATE,last_payment_time TIME, payment_datetime DATETIME);                              
   desc Subscription;
create table Users(user_id INT,username VARCHAR(50),email VARCHAR(100),interests SET('Music','Gaming','Education','Technology','Vlogs','Comedy'),account_status ENUM('active','inactive','blocked'),created_at TIMESTAMP);
desc Users;
create table watch_history(watch_id INT, watch_date DATE,watch_time TIME,watch_duration_seconds INT,completion_percentage DECIMAL(5,2),video_quality SET('360p','480p','720p','1080p','4K'));
alter table Subscription Rename to Subscriptions;
desc watch_history;
create table Notifications( notification_id INT,notification_type ENUM('NewVideo','CommentReply','LiveStream','Subscription'), priority SET('Low','Medium','High'),message TEXT,sent_at TIMESTAMP);
desc Notifications;